# Configuration file for Harder Wardens plugin

# WARDEN'S DIFFICULTY LEVEL
warden_difficulty: NORMAL   # EASY | NORMAL | HARD | NIGHTMARE | INSANE | CUSTOM

# Settings for custom difficulty - CUSTOM has to be set as the warden's difficulty
warden_health: 100   # Minimum = 1 | Maximum = 1024
warden_damage: 1.0   # Minimum = 0.1 | Maximum = 100.0
warden_loot_option_1: 1   # Details for each loot tier below
warden_loot_option_2: 2   # Details for each loot tier below

# Details for each difficulty:

# Difficulty EASY details:
#   Warden's Health: 300 hp (150 hearts)
#   Warden's Damage: 0.5x multiplier
#   Loot options: 1 and 2

# Difficulty NORMAL details:
#   Warden's Health: 500 hp (250 hearts)
#   Warden's Damage: 1.5x multiplier
#   Loot options: 3 and 4

# Difficulty HARD details:
#   Warden's Health: 700 hp (350 hearts)
#   Warden's Damage: 2.5x multiplier
#   Loot options: 5 and 6

# Difficulty NIGHTMARE details:
#   Warden's Health: 900 hp (450 hearts)
#   Warden's Damage: 3.5x multiplier
#   Loot options: 7 and 8

# Difficulty INSANE details:
#   Warden's Health: 1024 hp (512 hearts)
#   Warden's Damage: 4.5x multiplier
#   Loot options: 9 and 10

# Details for each loot option:
# These loot options might get changed in the future, if you have any ideas on what to add or remove from them, please give us a feedback, thank you!

# Loot 0: This one disables loot
# Loot 1: 3x Iron Ingots, 4x Amethyst Shards, 5x Lapis Lazuli
# Loot 2: 1x Diamond, 1x Golden Apple, 1x Enchanted Book
# Loot 3: 4x Gold Ingots, 6x Redstones, 2x Emeralds
# Loot 4: 1x Netherite Scrap, 2x Ender Pearls, 1x Enchanted Book
# Loot 5: 5x Nether Quartz, 2x Blaze Rods, 2x Diamonds
# Loot 6: 1x Totem of Undying, 1x Enchanted Tool, 1x Enchanted Book
# Loot 7: 3x Diamonds, 3x Ender Pearls, 2x Blaze Powders
# Loot 8: 2x Netherite Scraps, 1x Enchanted Armor Piece, 1x Enchanted Golden Apple
# Loot 9: 3x Netherite Scraps, 1x End Crystal, 2x Ghast Tears
# Loot 10: 1x Netherite Ingot, 1x Totem of Undying, 1x Enchanted Netherite Weapon

# Version 1.2 works for MC versions 1.21 - 1.21.11
# End of config file